### ISSUE TITLE
Tables are too wide

### ISSUE THREAD

**Issue by jkfindeisen** [AbberiorInstruments/ImspectorDocs#1]
See [Shortcut table](http://imspectordocs.readthedocs.io/en/latest/howtos.html#shortcuts). Tables are too wide and not wrapped within a column even after increasing the width of the content part of the theme. It seems the width of the tables is fixed and determined by the content and in general way too wide.

I would expect columns to be have a width in percent of the total available width and then wraping of the lines in the cells of the column. This does not happen. Am I supposed to do that manually in my rst file and just guess or try repeatedly? If so, I would not use tables anymore.

I fix would be some custom css rules that make the width of tables flexible and if this is not possible, maybe pure html tables in rst.

**Comment by mpibpc-mroose** [comment]
This is a prblem related to ReadTheDocs Template. See https://github.com/snide/sphinx_rtd_theme/issues/259. I will try to add a fix for that.

**Comment by mpibpc-mroose** [comment]
wrong issue number mentioned in push.
